name: Run paho tests

on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      version:
        required: true
  repository_dispatch:
    types: [run_tests]

jobs:

    run_paho_tests:

        runs-on: ubuntu-latest

        steps:
        - name: Install docker-compose
          run: |
            sudo curl -L "https://github.com/docker/compose/releases/download/1.25.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
        - uses: actions/checkout@v1
        - name: get deps
          run: |
            if [ ${{ github.event_name}} = 'repository_dispatch' ]; then
                version=${{ github.event.client_payload.version }}
            elif [ ${{ github.event_name}} = 'workflow_dispatch' ]; then
                version=${{ github.event.inputs.version }}
            else
                version=$(echo ${{ github.ref }} | sed -r  "s ^refs/heads/|^refs/tags/(.*) \1 g")
            fi

            docker run -i --rm \
              -e EMQX_DEPS_DEFAULT_VSN=$version \
              -v $(pwd):/emqx-rel \
              -w /emqx-rel \
              emqx/build-env:erl22.3-debian10 \
              bash -c "make deps-emqx"
        - name: make emqx image
          run: TARGET=emqx/emqx make docker-build
        - name: make paho tests
          run: TARGET=emqx/emqx PAHO_BRANCH="develop-4.0" make -C .ci/paho_tests test
